# _BinaryToHeader.cmake
# Convert a binary file to a C/C++ header with a static byte array.
#
# Invoke with:
#   cmake -DINPUT=<path/to/file.bin> -DOUTPUT=<path/to/file.h>
#         [-DSYMBOL=<identifier>] [-DCHUNK=<bytes_per_line>] -P _BinaryToHeader.cmake
#
# Notes:
# - Uses only built-in CMake commands (file(READ ... HEX), string(), math()).
# - Emits a header guard and C-compatible declarations.
# - Uses 'static' to avoid multiple-definition issues when included in many TUs.
#
# References:
#   - file(READ ... HEX) docs (CMake): reads binary and returns lowercase hex. 
#   - string()/math() docs (CMake): used for chunking and formatting.
#   - Similar pure-CMake "bin2h" approaches inspired by prior community work.
#     (We reimplemented/adapted to your project’s needs.)
#
#   These docs are authoritative:
#     https://cmake.org/cmake/help/latest/command/file.html
#     https://cmake.org/cmake/help/latest/command/string.html

# ---- Validate inputs ---------------------------------------------------------
if(NOT DEFINED INPUT)
  message(FATAL_ERROR "_BinaryToHeader.cmake: -DINPUT=<path> is required.")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "_BinaryToHeader.cmake: -DOUTPUT=<path> is required.")
endif()
if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "_BinaryToHeader.cmake: INPUT file does not exist: ${INPUT}")
endif()

# Optional settings
if(NOT DEFINED CHUNK)
  set(CHUNK 16) # bytes per line (nice hex grouping)
endif()

# ---- Derive a safe symbol if not provided -----------------------------------
# Base it on the input filename, lowercase, non [A-Za-z0-9_] → '_'
get_filename_component(_BASE "${INPUT}" NAME)
string(TOLOWER "${_BASE}" _SYM)
string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _SYM "${_SYM}")
# If the symbol starts with a digit, prefix with underscore
string(REGEX MATCH "^[0-9]" _LEADS_DIGIT "${_SYM}")
if(_LEADS_DIGIT)
  set(_SYM "_${_SYM}")
endif()
if(NOT DEFINED SYMBOL OR SYMBOL STREQUAL "")
  set(SYMBOL "${_SYM}")
endif()

# Header guard derived from OUTPUT path + SYMBOL
get_filename_component(_OUTNAME "${OUTPUT}" NAME_WE)
set(_GUARD "COLONYGAME_EMBED_${_OUTNAME}_${SYMBOL}_H_")
string(TOUPPER "${_GUARD}" _GUARD)

# ---- Read the file as hex ----------------------------------------------------
# file(READ ... HEX) returns a contiguous lowercase hex string: "ff00ab..."
# We'll convert it to "0xff, 0x00, 0xab, ..." with CHUNK bytes per line.
file(SIZE "${INPUT}" _BIN_SIZE)
file(READ "${INPUT}" _HEX HEX)  # authoritative, built-in approach
# https://cmake.org/cmake/help/latest/command/file.html  (READ ... HEX)

string(LENGTH "${_HEX}" _HEX_LEN)
if(_HEX_LEN EQUAL 0)
  set(_NBYTES 0)
else()
  math(EXPR _NBYTES "${_HEX_LEN} / 2")
endif()

# ---- Build formatted hex lines ----------------------------------------------
set(_CONTENT "")
if(_NBYTES GREATER 0)
  math(EXPR _LAST_IDX "${_NBYTES} - 1")
  set(_COUNT 0)
  set(_LINE "  ")

  foreach(i RANGE 0 ${_LAST_IDX})
    # Extract two hex chars for this byte
    math(EXPR _POS "2*${i}")
    string(SUBSTRING "${_HEX}" ${_POS} 2 _B)
    # Append separator if not the first on this line
    if(NOT _COUNT EQUAL 0)
      set(_LINE "${_LINE}, ")
    endif()
    set(_LINE "${_LINE}0x${_B}")

    math(EXPR _COUNT "${_COUNT}+1")
    if(_COUNT EQUAL ${CHUNK} OR i EQUAL ${_LAST_IDX})
      # Terminate the current line
      set(_CONTENT "${_CONTENT}${_LINE}\n")
      set(_LINE "  ")
      set(_COUNT 0)
    endif()
  endforeach()
endif()

# ---- Emit header -------------------------------------------------------------
# Keep everything in the build dir (OUTPUT is expected to be there).
# https://discourse.cmake.org/t/trying-to-generate-header-file-using-add-custom-command-resulted-limping-build/6621
file(WRITE "${OUTPUT}" "/* Auto-generated by _BinaryToHeader.cmake. Do not edit.
   Source : ${INPUT}
   Size   : ${_BIN_SIZE} bytes
*/\n")
file(APPEND "${OUTPUT}" "#ifndef ${_GUARD}\n#define ${_GUARD}\n\n")
file(APPEND "${OUTPUT}" "#include <stddef.h>\n\n")
# C + C++ friendly linkage (static => internal; extern \"C\" not needed here)
file(APPEND "${OUTPUT}" "/* ${SYMBOL}: embedded binary blob */\n")
file(APPEND "${OUTPUT}" "static const unsigned char ${SYMBOL}[] = {\n")
if(_NBYTES GREATER 0)
  file(APPEND "${OUTPUT}" "${_CONTENT}")
endif()
file(APPEND "${OUTPUT}" "};\n")
file(APPEND "${OUTPUT}" "static const size_t ${SYMBOL}_size = sizeof(${SYMBOL});\n\n")
file(APPEND "${OUTPUT}" "#endif /* ${_GUARD} */\n")
