# cmake/cg_find.cmake
include_guard(GLOBAL)

function(cg_require_program OUT_VAR)
  set(options)
  set(one)
  set(multi NAMES HINT_DIRS PATH_SUFFIXES)
  cmake_parse_arguments(ARG "${options}" "${one}" "${multi}" ${ARGN})
  if(NOT ARG_NAMES)
    message(FATAL_ERROR "cg_require_program: NAMES <prog>... is required")
  endif()
  find_program(_p NAMES ${ARG_NAMES} HINTS ${ARG_HINT_DIRS} PATH_SUFFIXES ${ARG_PATH_SUFFIXES})
  if(NOT _p)
    find_program(_p NAMES ${ARG_NAMES})
  endif()
  if(NOT _p)
    message(FATAL_ERROR "Program not found: ${ARG_NAMES}")
  endif()
  set(${OUT_VAR} "${_p}" PARENT_SCOPE)
endfunction()
