function(cg_print_config_summary)
    message(STATUS "Colony Config Summary")
    message(STATUS "  COLONY_BUILD_TESTS:         ${COLONY_BUILD_TESTS}")
    message(STATUS "  COLONY_ENABLE_TRACY:        ${COLONY_ENABLE_TRACY}")
    message(STATUS "  COLONY_WARNINGS_AS_ERRORS:  ${COLONY_WARNINGS_AS_ERRORS}")
    message(STATUS "  COLONY_WERROR:              ${COLONY_WERROR}")
    message(STATUS "  COLONY_ENABLE_SANITIZERS:   ${COLONY_ENABLE_SANITIZERS}")
    message(STATUS "  COLONY_ASAN:                ${COLONY_ASAN}")
    message(STATUS "  COLONY_UBSAN:               ${COLONY_UBSAN}")
    message(STATUS "  COLONY_HLSL_MODEL:          ${COLONY_HLSL_MODEL}")
endfunction()
