# cmake/NoFlagsInSources.cmake
function(colony_verify_no_flags_in_sources tgt)
  if(NOT TARGET "${tgt}")
    return()
  endif()
  get_target_property(_srcs "${tgt}" SOURCES)
  if(NOT _srcs)
    return()
  endif()
  set(_bad "")
  foreach(_s IN LISTS _srcs)
    if(_s MATCHES "^([/-]O[0-3]|[/-]RTC[^;]*|/Z[^;]*|/G[^;]*)$")
      list(APPEND _bad "${_s}")
    elseif(_s MATCHES "^\\$<[^>]*:([/\\-](O[0-3]|RTC[^>]*|Z[^>]*|G[^>]*))>")
      list(APPEND _bad "${_s}")
    elseif(_s MATCHES "^\\$<[01]:/[^>]*>")
      list(APPEND _bad "${_s}")
    endif()
  endforeach()
  if(_bad)
    message(FATAL_ERROR
      "Compile flags or generator expressions were added as *sources* of target '${tgt}'.\n"
      "Move them to target_compile_options()/target_link_options(). Offending entries:\n  ${_bad}\n")
  endif()
endfunction()
