#pragma once

#include "input/InputEvent.h"

#include <array>
#include <bitset>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <span>
#include <string_view>

namespace colony::input {

// High-level actions produced by the input mapper.
//
// This enum is intentionally small (prototype), but it's the seam where future
// gameplay actions should be added.
//
// Notes:
//  - "MoveForwardFast" exists mainly to demonstrate chord bindings (Shift+W).
//  - CameraOrbit/CameraPan exist so the camera no longer depends on raw mouse
//    button masks; mouse buttons are treated as bindable inputs.
enum class Action : std::uint8_t {
    MoveForward = 0,
    MoveBackward,
    MoveLeft,
    MoveRight,
    MoveDown,
    MoveUp,

    // Example chord action (Shift+W by default).
    MoveForwardFast,

    // Modifier-style action that affects movement speed.
    SpeedBoost,

    // Mouse-driven camera actions (bindable).
    CameraOrbit,
    CameraPan,

    // Mouse wheel camera zoom (impulse-style; WheelUp/WheelDown by default).
    CameraZoomIn,
    CameraZoomOut,

    // Developer QOL: reload input bindings from disk (defaults to F5).
    ReloadBindings,

    // Prototype persistence.
    SaveWorld,
    LoadWorld,

    // Prototype editor QOL.
    Undo,
    Redo,

    // Prototype build-planning QOL.
    PlanPriorityUp,
    PlanPriorityDown,

    Count
};

// Discrete action transitions generated by the mapper.
//
// The goal is for gameplay code to react to *actions* rather than raw keys.
enum class ActionEventType : std::uint8_t {
    Pressed = 0,
    Released = 1,
};

struct ActionEvent {
    Action action = Action::MoveForward;
    ActionEventType type = ActionEventType::Pressed;
};

struct MovementAxes {
    // x: strafe (right - left)
    // y: forward/back (forward - backward)
    // z: vertical (up - down)
    float x = 0.f;
    float y = 0.f;
    float z = 0.f;
};

// Maps raw input events (keyboard + mouse buttons) to high-level actions.
//
// Features:
//  - multiple bindings per action
//  - chord bindings (e.g., Shift+W)
//  - JSON/INI configurable bindings (optional; defaults are compiled-in)
//  - action transition stream (pressed/released)
class InputMapper {
public:
    InputMapper() noexcept;

    void SetDefaultBinds() noexcept;

    // Attempts to load bindings from a JSON/INI file.
    //
    // If loading fails, existing binds are preserved.
    bool LoadFromFile(const std::filesystem::path& path) noexcept;

    // Convenience: searches for a bindings file in a few common locations,
    // starting at the current working directory and walking up a few parents.
    //
    // Looks for (in order):
    //   winpath::config_dir()/input_bindings.json   (Windows per-user override)
    //   winpath::config_dir()/input_bindings.ini    (Windows per-user override)
    //   assets/config/input_bindings.json
    //   assets/config/input_bindings.ini
    //   input_bindings.json
    //   input_bindings.ini
    bool LoadFromDefaultPaths() noexcept;

    // Clears all tracked input state (useful on focus loss).
    void ClearState() noexcept;

    // Multiple bindings per action.
    void ClearBindings(Action action) noexcept;

    // Adds a chord binding for an action. A chord is "all of these codes down".
    //
    // Example:
    //   { colony::input::bindings::kVK_SHIFT, 'W' }
    //   { kMouseButtonLeft }
    void AddBinding(Action action, std::span<const std::uint32_t> chord) noexcept;

    // Convenience for a single-code binding.
    void AddBinding(Action action, std::uint32_t code) noexcept
    {
        AddBinding(action, std::span<const std::uint32_t>(&code, 1));
    }

    // Per-frame consumption.
    void BeginFrame() noexcept;

    // Consume a single event (updates internal state, may emit action transitions).
    // Returns true if this event caused any action transitions.
    bool ConsumeEvent(const InputEvent& ev) noexcept;

    // Consume a batch of events. Returns true if any action transitions occurred.
    bool Consume(std::span<const InputEvent> events) noexcept;

    // Action transitions generated since BeginFrame().
    [[nodiscard]] std::span<const ActionEvent> ActionEvents() const noexcept;

    [[nodiscard]] bool IsDown(Action action) const noexcept;

    [[nodiscard]] MovementAxes GetMovementAxes() const noexcept;

    // --- Introspection helpers (debug UI / bindings editor) ---
    [[nodiscard]] std::size_t BindingCount(Action action) const noexcept;
    [[nodiscard]] std::span<const std::uint16_t> BindingChord(Action action, std::size_t bindingIndex) const noexcept;

    // Canonical action name used in config files.
    [[nodiscard]] static const char* ActionName(Action action) noexcept;

private:
    static constexpr std::size_t kActionCount = static_cast<std::size_t>(Action::Count);

    // Tuning knobs.
    static constexpr std::size_t kMaxBindingsPerAction = 16;
    static constexpr std::size_t kMaxChordButtons = 4;
    static constexpr std::size_t kMaxActionEvents = 256;

    // Input codes are small integers. We reserve some headroom beyond what the
    // prototype currently needs.
    static constexpr std::size_t kMaxInputCodes = 512;
    static_assert(kInputCodeCount <= kMaxInputCodes, "Increase kMaxInputCodes if you add more input codes.");

    struct Chord {
        std::array<std::uint16_t, kMaxChordButtons> codes{};
        std::uint8_t count = 0;
    };

    static constexpr std::size_t ToIndex(Action a) noexcept
    {
        return static_cast<std::size_t>(a);
    }

    void PushActionEvent(Action action, ActionEventType type) noexcept;
    [[nodiscard]] bool ComputeActionDown(Action action) const noexcept;
    void RecomputeActionStatesNoEvents() noexcept;
    void RefreshActionsAndEmitTransitions() noexcept;

    // Config parsing helpers.
    bool LoadFromJsonText(std::string_view text) noexcept;
    bool LoadFromIniText(std::string_view text) noexcept;

    std::bitset<kMaxInputCodes> m_down{};

    // Chord bindings.
    std::array<std::array<Chord, kMaxBindingsPerAction>, kActionCount> m_binds{};
    std::array<std::uint8_t, kActionCount> m_bindCounts{};

    // Cached action-down state.
    std::array<bool, kActionCount> m_actionDown{};

    // Discrete action events (pressed/released).
    std::array<ActionEvent, kMaxActionEvents> m_actionEvents{};
    std::size_t m_actionEventCount = 0;
    std::size_t m_droppedActionEvents = 0;
};

} // namespace colony::input
