name: ci
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Skip Linux since the project is Windows-only
      - name: Skip on non-Windows (Windows-only project)
        if: runner.os != 'Windows'
        run: echo "Skipping build on ${{ runner.os }} (project is Windows-only)."

      # Set up MSVC environment for Visual Studio generator
      - name: Setup MSVC dev environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # Configure with Visual Studio (multi-config). Do NOT pass CMAKE_BUILD_TYPE here.
      - name: Configure
        if: runner.os == 'Windows'
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      # Build the chosen configuration
      - name: Build
        if: runner.os == 'Windows'
        run: cmake --build build --config RelWithDebInfo --parallel

      # Run tests for that configuration
      - name: Test
        if: runner.os == 'Windows'
        run: ctest --test-dir build -C RelWithDebInfo --output-on-failure
