name: CI (Windows)

on:
  push: { branches: ['**'] }
  pull_request: { branches: ['**'] }
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # needed for release uploads

jobs:
  build-and-test-windows:
    name: Build & Test (Windows)
    runs-on: windows-latest
    defaults: { run: { shell: pwsh } }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0, submodules: recursive }

      - name: Set up MSVC (VS 2022)
        uses: ilammy/msvc-dev-cmd@v1
        with: { arch: x64 }

      - name: Cache CMake/vcpkg deps
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
            C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt', 'vcpkg.json', 'CMakePresets.json') }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Configure (CMake)
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A x64
          -DBUILD_TESTING=ON

      - name: Build (Release)
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build -C Release --output-on-failure

      - name: Package (zip)
        run: |
          New-Item -ItemType Directory -Path out -Force | Out-Null
          $dest = "out/ColonyGame-${{ github.ref_name }}-win64.zip"
          Compress-Archive -Path `
            "build/**/*.exe","build/**/*.dll","build/**/*.pdb","res/*" `
            -DestinationPath $dest -Force
          Write-Host "Packaged $dest"

      - name: Upload build artifacts (PRs)
        if: ${{ github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-artifacts
          path: out/*.zip

      - name: Publish release (tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/*.zip
