name: Windows CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Windows-safe filenames
        shell: pwsh
        run: |
          $invalid = @()
          git ls-tree -r --name-only HEAD | ForEach-Object {
            # Invalid characters or reserved device names on Windows
            if ($_ -match '[:<>\"|?*]' -or $_ -match '(^|[\\/])(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.|[\\/]|$)') {
              $invalid += $_
            }
          }
          if ($invalid.Count -gt 0) {
            Write-Host "❌ Invalid Windows paths found:" -ForegroundColor Red
            $invalid | ForEach-Object { Write-Host "  $_" }
            exit 1
          } else {
            Write-Host "✅ All file names are Windows-safe."
          }

      - name: Configure CMake (MSVC)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (Release)
        run: cmake --build build --config Release --parallel
